---
- name: NGINX | Set secure nginx config
  template: src=nginx.conf.j2 dest={{ nginx_root}}/nginx.conf
  notify: restart nginx
  tags: [security,configuration,nginx]

# - name: Create the configurations for sites
#   template: src=site.conf.j2 dest={{ nginx_root }}/conf.d/{{ item }}.conf
#   with_items: "{{ nginx_sites.keys() | difference(nginx_remove_sites) }}"
#   notify: restart nginx
#   tags: [configuration,nginx]

- name: Create the configuration file for vHosts
  template:
    src: sites.conf.j2
    dest: "{{ nginx_root }}/conf.d/sites.conf"
    mode: 0644
  notify:
    - reload nginx
  tags: [configuration,nginx]