---
- name: Ensure log directory exists
  become: true
  file: path={{ nginx_log_dir }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0755
  tags: [configuration,nginx]

- name: NGINX | Ensure log directory per vhost exists
  become: true
  file: path={{ nginx_log_dir }}/{{ item.nginx_vhost }} state=directory owner={{nginx_user}} group={{nginx_group}} mode=0755
  with_items: "{{ nginx_sites }}"
  tags: [configuration,nginx]