---
- name: NGINX | Generate dhparam file
  # -dsaparm => https://goo.gl/OkbDqi for faster generation
  command: openssl dhparam -dsaparam -out /etc/ssl/dhparam.pem 4096 creates=/etc/ssl/dhparam.pem
  tags: [installation,security,nginx]

- name: NGINX | Ensure ssl dir exists
  become: true
  file: path={{ nginx_root }}/ssl/{{ item.nginx_ssl_cn }} state=directory
  with_items: "{{ nginx_sites }}"
  tags: [installation,security,nginx]

- name: NGINX | Create self-signed SSL cert
  become: true
  shell: >
    openssl req -x509 -nodes -subj '/
    /C={{ item.nginx_ssl_c }}
    /ST={{ item.nginx_ssl_st }}
    /L={{ item.nginx_ssl_l }}
    /O={{ item.nginx_ssl_o }}
    /CN={{ item.nginx_ssl_cn }}
    ' -days 365 -newkey rsa:2048 
    -out /etc/nginx/ssl/{{ item.nginx_ssl_cn }}/cert.pem
    -keyout /etc/nginx/ssl/{{ item.nginx_ssl_cn }}/privkey.key 
    creates=/etc/nginx/ssl/{{ item.nginx_ssl_cn }}/cert.pem
  with_items: "{{ nginx_sites }}"
  notify: restart nginx
  tags: [installation,security,nginx]