---
- name: NGINX | Generate dhparam file
  # -dsaparm => https://goo.gl/OkbDqi for faster generation
  command: openssl dhparam -dsaparam -out /etc/ssl/dhparam.pem 4096 creates=/etc/ssl/dhparam.pem
  tags: [installation,security,nginx]

- name: NGINX | Ensure ssl dir exists
  become: true
  file: path={{ nginx_root }}/ssl/{{ nginx_ssl_cn }} state=directory
  tags: [installation,security,nginx]

- name: NGINX | Create self-signed SSL cert
  become: true
  shell: >
    openssl req -x509 -nodes -subj '/
    /C={{ nginx_ssl_c }}
    /ST={{ nginx_ssl_st }}
    /L={{ nginx_ssl_l }}
    /O={{ nginx_ssl_o }}
    /CN={{ nginx_ssl_cn }}
    ' -days 365 -newkey rsa:2048 
    -out /etc/nginx/ssl/{{ nginx_ssl_cn }}/cert.pem
    -keyout /etc/nginx/ssl/{{ nginx_ssl_cn }}/privkey.key 
    creates=/etc/nginx/ssl/{{ nginx_ssl_cn }}/cert.pem
  notify: restart nginx
  tags: [installation,security,nginx]

- name: NGINX | Ensures {{nginx_docroot}}/ dir exists
  file: path={{nginx_docroot}} state=directory
  tags: [installation,security,nginx]

- name: NGINX | Add SSL config
  template: src=ssl.tpl dest={{ nginx_root }}/ssl.conf
  notify: restart nginx
  tags: [installation,security,nginx]

- name: NGINX | Set secure nginx config
  template: src=nginx.conf.j2 dest={{ nginx_root}}/nginx.conf
  notify: restart nginx
  tags: [installation,security,nginx]